-- 코드를 입력하세요
SELECT HISTORY_ID, 
CASE
    WHEN B.TYPE IS NULL THEN ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
    ELSE ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
END FEE
FROM 
(
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) A RIGHT JOIN
(
    SELECT A.CAR_ID, HISTORY_ID, DAILY_FEE, START_DATE, END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 89 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) >= 6 THEN '7일 이상'
    END TYPE
    FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
) B ON A.DURATION_TYPE = B.TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;